### ISSUE TITLE
1px offset on draw circle

### ISSUE THREAD

**Issue by PrimaIVoid** [GabrielLasso/drawim#3]
Seems like the proc `circleFill(mouseX(), mouseY(), 20)` draws an additional black pixel on the middle-right side of the Circle (but not on the left side). I have not tested if also other primitives have this same behaviour
This visual bug is reproducible by running  `mouse.nim` example as shown:
https://media.discordapp.net/attachments/706542664643772436/888057325812858910/pixelOff.png?width=594&height=423

**Comment by GabrielLasso** [comment]
Maybe that happens due to floating point rounding... I will check it out

Thanks for reporting

**Comment by GabrielLasso** [comment]
This should fix https://github.com/GabrielLasso/drawim/pull/4
