### ISSUE TITLE
Examples are flickering on macOS

### ISSUE THREAD

**Issue by filipux** [GabrielLasso/drawim#7]
Many of the examples are flickering really fast on my computer with macOS Mojave 10.14.4

One example from running `nim c -r pacman.nim` with Nim v1.4.8, though in reality the flickering is much faster:

![ezgif-6-5c825f6b0f7c](https://user-images.githubusercontent.com/7125733/133934831-be95ca01-e4e9-40e2-b2fd-9b6d7a75ea4e.gif)

**Comment by GabrielLasso** [comment]
I don't have a macOS to test... Try removing the `background` call and see what happens (by the gif, it seems that only the background is flickering, right?)

**Comment by filipux** [comment]
I did some investigation and I think the problem might be caused by the high density "retina" screen on my macbook pro. In the flickering image above, you can see the lower quadrant isn't flickering. I figured this could have something to do with window size not being equal to buffer sizes. Just to test things I multiplied the `window_height` and `window_width` by 2 in the `glCopyPixels()` call in `opengl_backend.nim` and it seems to solve the flickering issues.

![image](https://user-images.githubusercontent.com/7125733/134019435-269d4bf5-dfa1-4e38-ba79-c8abfdb8edb6.png)

I guess you would have to check the dpi of the screen and scale all drawing buffers accordingly to solve the problem properly.

On the other hand, the best solution would probably be to also scale all drawing operations. A single pixel line is very small on my screen and would look better if rendered at 2x the thickness.

**Comment by GabrielLasso** [comment]
That makes sense.

I'll see if I can check the DPI of the screen, and if I can't I will just multiply by 2 to support both normal and retina screens

**Comment by filipux** [comment]
This code returns the correct pixel_density value of 2 for my computer when run in `initialize()` right after setting up the window:
```
  var buffer_width, buffer_height:cint
  window.getFramebufferSize(addr(buffer_width), addr(buffer_height))
  pixel_density = buffer_width div window_width
```

**Comment by GabrielLasso** [comment]
@filipux can you try on https://github.com/GabrielLasso/drawim/pull/8 branch?

I was on my regular work until now, I only looked at the code now.

**Comment by GabrielLasso** [comment]
> This code returns the correct pixel_density value of 2 for my computer when run in `initialize()` right after setting up the window:
> 
> ```
>   var buffer_width, buffer_height:cint
>   window.getFramebufferSize(addr(buffer_width), addr(buffer_height))
>   pixel_density = buffer_width div window_width
> ```

This might be better that what I done, as it don't change the `window_width` and `window_height`, I will use it :smile:

**Comment by filipux** [comment]
Those changes seem to solve the flickering issues 👍
